imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: pl

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_theme: 'bootstrap_3_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8mb4
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    host: '%mailer_host%'

easy_admin:
    site_name: 'dieta <em style="color: red;">trening</em>'
    design:
        brand_color: '#164C1C'
    list:
        title: 'list.%%entity_label%%'
    show:
        title: '%%entity_label%% (#%%entity_id%%)'
    entities:
        User:
            class: AppBundle\Entity\User
        UserData:
            class: AppBundle\Entity\UserData
        Food:
            class: AppBundle\Entity\Food
        Category:
            class: AppBundle\Entity\Category
        MyFood:
            class: AppBundle\Entity\MyFood
        UserFood:
            class: AppBundle\Entity\UserFood
        Subcategory:
            class: AppBundle\Entity\Subcategory
        CardioCategory:
            class: AppBundle\Entity\CardioCategory
        CardioTraining:
            class: AppBundle\Entity\CardioCategory
        UserCardio:
            class: AppBundle\Entity\UserCardio
        MyStrengthTraining:
            class: AppBundle\Entity\MyStrengthTraining
        ProfileImage:
            class: AppBundle\Entity\ProfileImage
            list:
                fields:
                    - { property: 'profileImage', type: 'image', base_path: '/dieta_trening/web/' }
        StrengthTraining:
            class: AppBundle\Entity\StrengthTraining
        UserStrengthTraining:
            class: AppBundle\Entity\UserStrengthTraining
        UserStrengthTrainingCollection:
            class: AppBundle\Entity\UserStrengthTrainingCollection
        StrengthTrainingCategory:
            class: AppBundle\Entity\StrengthTrainingCategory
        StrengthTrainingExercise:
            class: AppBundle\Entity\StrengthTrainingExercise
        UserStrengthExerciseCollection:
            class: AppBundle\Entity\UserStrengthExerciseCollection
