imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: pl

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_theme: 'bootstrap_3_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8mb4
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    host: '%mailer_host%'

easy_admin:
    site_name: 'dieta <em style="color: red;">trening</em>'
    design:
        brand_color: '#164C1C'
    list:
        title: 'list.%%entity_label%%'
        actions:
            - { name: 'show', icon: 'search', label: '' }
            - { name: 'edit', icon: 'pencil', label: '' }
            - { name: 'delete', icon: 'remove', label: '' }
            - { name: 'new', icon: 'plus-square-o', label: 'new' }
            - { name: 'search', icon: 'search', label: 'search' }
    show:
        title: '%%entity_label%% (#%%entity_id%%)'
    edit:
        title: '%%entity_label%%_edit'
    new:
        title: 'New %%entity_label%%'
    entities:
        User:
            class: AppBundle\Entity\User
            export_path: '%kernel.root_dir/../var/export/user'
            password: { algorithm: 'bcrypt', cost: 12 }
        UserData:
            class: AppBundle\Entity\UserData
            form:
                fields: ['age', 'weight', 'height', 'gender', 'calories', { property: 'date', type: 'datetime' }]
        Food:
            class: AppBundle\Entity\Food
            form:
        Category:
            class: AppBundle\Entity\Category
        MyFood:
            class: AppBundle\Entity\MyFood
        UserFood:
            class: AppBundle\Entity\UserFood
            form:
                fields: ['quantity', 'meal', 'calories', 'totalProtein', 'fat', 'carbohydrates', 'productId', 'myProductId', 'userId', { property: 'date', type: 'datetime' }]
        Subcategory:
            class: AppBundle\Entity\Subcategory
        CardioCategory:
            class: AppBundle\Entity\CardioCategory
        CardioTraining:
            class: AppBundle\Entity\CardioCategory
        UserCardio:
            class: AppBundle\Entity\UserCardio
        MyStrengthTraining:
            class: AppBundle\Entity\MyStrengthTraining
        ProfileImage:
            class: AppBundle\Entity\ProfileImage
            list:
                fields:
                    - { property: 'profileImage', type: 'image', base_path: '/dieta_trening/web/' }
        StrengthTraining:
            class: AppBundle\Entity\StrengthTraining
        UserStrengthTraining:
            class: AppBundle\Entity\UserStrengthTraining
        UserStrengthTrainingCollection:
            class: AppBundle\Entity\UserStrengthTrainingCollection
        StrengthTrainingCategory:
            class: AppBundle\Entity\StrengthTrainingCategory
        StrengthTrainingExercise:
            class: AppBundle\Entity\StrengthTrainingExercise
        UserStrengthExerciseCollection:
            class: AppBundle\Entity\UserStrengthExerciseCollection

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations
    organize_migrations: false # Version >= 1.2, possible values are: "BY_YEAR", "BY_YEAR_AND_MONTH", false
    custom_template: ~ # Version >= 1.2, path to your custom migrations template
